name: Test

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install libwebkit2gtk-4.0-dev \
            build-essential \
            curl \
            wget \
            libssl-dev \
            libgtk-3-dev \
            squashfs-tools

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-02-23
          override: true
          components: rustfmt, clippy

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install Node dependencies
        run: |
          yarn install

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            src-tauri/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build assets
        run: |
          yarn build

      - name: Set opt level
        run: |
          sed -i -e 's/opt-level = 3/opt-level = 0/g' src-tauri/Cargo.toml

      - name: Cargo Check
        run: |
          cd src-tauri && cargo check

      - name: Cargo Fmt
        run: |
          cd src-tauri && cargo fmt -- --check

      - name: Cargo Clippy
        run: |
          cd src-tauri && cargo clippy -- -D warnings

  test-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-02-23
          override: true
          components: rustfmt, clippy

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install Node dependencies
        run: |
          yarn install

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            src-tauri/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build assets
        run: |
          yarn build

      - name: Set opt level
        run: |
          sed -i -e 's/opt-level = 3/opt-level = 0/g' src-tauri/Cargo.toml

      - name: Cargo Check
        run: |
          cd src-tauri && cargo check

      - name: Cargo Fmt
        run: |
          cd src-tauri && cargo fmt -- --check

      - name: Cargo Clippy
        run: |
          cd src-tauri && cargo clippy -- -D warnings
